using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Security.Cryptography;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using ModelSpace;

public static class EnvironmentPackageBuilder
{
    static string Root=>CharacterPackageBuilder.Root;
    static string Assets=>"Assets/EnvironmentPackages";
    public static string CatalogHash { get { using(var sha=SHA256.Create()) return string.Concat(sha.ComputeHash(File.ReadAllBytes(Path.Combine(Root,"ios/CharacterHost/Resources/EnvironmentCatalog.json"))).Select(b=>b.ToString("x2"))); } }
    [Serializable] class Catalog { public int schemaVersion=1,apiMajor=1;public EnvironmentManifest[] environments; }
    public static void Preflight()
    {
        var info=new System.Diagnostics.ProcessStartInfo(Path.Combine(Root,".local/character-sdk-venv/bin/python"),"\""+Path.Combine(Root,"scripts/validate_environments.py")+"\"") {UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,WorkingDirectory=Root};
        using(var p=System.Diagnostics.Process.Start(info)) {string output=p.StandardOutput.ReadToEnd(),error=p.StandardError.ReadToEnd();p.WaitForExit();if(p.ExitCode!=0)throw new Exception("ENVIRONMENT_PREFLIGHT_FAILED: "+error+output);}
    }
    public static void Create(CharacterStudioDriver studio,Camera camera)
    {
        var director=studio.gameObject.AddComponent<EnvironmentDirector>();studio.environment=director;
        director.key=studio.key;director.fill=studio.fill;director.rim=studio.rim;director.oldGround=studio.oldGround;director.viewCamera=camera;
        var stages=new List<EnvironmentStage>();
        foreach(string kind in new[]{"builtins","imported"})
        foreach(string source in Directory.GetDirectories(Path.Combine(Root,"environment-packages",kind)).OrderBy(s=>s,StringComparer.Ordinal))
        {
            var m=JsonUtility.FromJson<EnvironmentManifest>(File.ReadAllText(Path.Combine(source,"environment.json")));
            string folder=Assets+"/"+m.id;Directory.CreateDirectory(folder);
            foreach(string file in Directory.GetFiles(source,"*",SearchOption.AllDirectories))
            { string target=Path.Combine(folder,file.Substring(source.Length+1));Directory.CreateDirectory(Path.GetDirectoryName(target));File.Copy(file,target,true); }
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            Transform geometry;
            if(m.source.kind=="builtin")
            {
                geometry=Array.Find(studio.rooms,r=>r.name==m.id);
                if(!geometry) geometry=OutdoorEnvironmentBuilder.Create(m.id);
                GroupBuiltin(geometry,m.id);
                m.bindings.surface=new[]{"Surface"};m.bindings.accent=geometry.Find("Decor/Accent").childCount>0 ? new[]{"Decor/Accent"} : Array.Empty<string>();m.bindings.decor=new[]{"Decor"};
                // Binding paths in built-in manifests are generated by the legacy authoring adapter.
                File.WriteAllText(folder+"/runtime.json",JsonUtility.ToJson(m,true));AssetDatabase.ImportAsset(folder+"/runtime.json");
            }
            else
            {
                string path=folder+"/"+m.source.model;
                var asset=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(!asset)throw new Exception("ENVIRONMENT_GLB_IMPORT_FAILED: "+m.id);
                geometry=UnityEngine.Object.Instantiate(asset).transform;
                foreach(var animator in geometry.GetComponentsInChildren<Animator>(true))UnityEngine.Object.DestroyImmediate(animator);
                foreach(var animation in geometry.GetComponentsInChildren<Animation>(true))UnityEngine.Object.DestroyImmediate(animation);
                foreach(var light in geometry.GetComponentsInChildren<Light>(true))UnityEngine.Object.DestroyImmediate(light);
                foreach(var importedCamera in geometry.GetComponentsInChildren<Camera>(true))UnityEngine.Object.DestroyImmediate(importedCamera);
                if(m.packageId=="app.xiaoban.examples.courtyard") RefinedEnvironmentBuilder.RefineCourtyard(geometry,m);
            }
            // Runtime-only art enrichment keeps the original XEP source/GLB untouched.
            File.WriteAllText(folder+"/runtime.json",JsonUtility.ToJson(m,true));AssetDatabase.ImportAsset(folder+"/runtime.json");
            var stage=new GameObject("Environment_"+m.id).AddComponent<EnvironmentStage>();
            geometry.SetParent(stage.transform,false);geometry.name="Geometry";geometry.gameObject.SetActive(true);
            geometry.localScale=Vector3.one*m.source.scale;geometry.localRotation=Quaternion.Euler(0,m.source.yaw,0);
            stage.geometry=geometry;stage.manifestAsset=AssetDatabase.LoadAssetAtPath<TextAsset>(folder+"/runtime.json");
            Validate(stage);stage.gameObject.SetActive(false);stages.Add(stage);
        }
        director.stages=stages.OrderBy(s=>s.Manifest.display.order).ToArray();
        director.Bind(1.7f);director.Configure(new StudioSettings());
        File.WriteAllText(Path.Combine(Root,"ios/CharacterHost/Resources/EnvironmentCatalog.json"),JsonUtility.ToJson(new Catalog {environments=director.stages.Select(s=>s.Manifest).ToArray()},true)+"\n");
    }
    static void GroupBuiltin(Transform root,string id)
    {
        if(root.Find("Surface") && root.Find("Decor/Accent")) return;
        var children=root.Cast<Transform>().ToArray();
        var surface=new GameObject("Surface").transform;surface.SetParent(root,false);
        var accent=new GameObject("Accent").transform;accent.SetParent(root,false);
        var decor=new GameObject("Decor").transform;decor.SetParent(root,false);accent.SetParent(decor,false);
        foreach(var t in children)
        {
            bool structural=t.name.Contains("Tree ") || t.name.Contains("Railing") || t.name.Contains("Stone terrace") || t.name.Contains("Path stone") || t.name.Contains("Floor") || t.name.Contains("wall") || t.name.Contains("Window") || t.name.Contains("Baseboard") || t.name.Contains("Curtain") || t.name.Contains("curtain") || t.name.Contains("Sky") || t.name.Contains("Sea") || t.name.Contains("Distant") || t.name.Contains("Deck") || t.name.Contains("Ground");
            if(t.name.Contains("Back wall") || t.name.Contains("Portrait backdrop") || t.name.Contains("Ground") || t.name.Contains("Deck"))t.SetParent(surface,true);
            else if(t.name.Contains("Flower") || t.name.Contains("Cushion"))t.SetParent(accent,true);
            else if(!structural)t.SetParent(decor,true);
        }
    }
    public static void Validate(EnvironmentStage stage)
    {
        var m=stage.Manifest;var renderers=stage.geometry.GetComponentsInChildren<Renderer>(true);
        if(renderers.Length==0 || renderers.Length>256)throw new Exception("ENVIRONMENT_RENDERER_BUDGET: "+m.id);
        var targets=new HashSet<Renderer>();
        foreach(string path in m.bindings.surface.Concat(m.bindings.accent))
        {
            var t=stage.geometry.Find(path);if(!t)throw new Exception("ENVIRONMENT_BINDING_MISSING: "+m.id+"/"+path);
            var list=t.GetComponentsInChildren<Renderer>(true);if(list.Length==0)throw new Exception("ENVIRONMENT_EMPTY_COLOR_BINDING");
            foreach(var r in list)if(!targets.Add(r))throw new Exception("ENVIRONMENT_COLOR_BINDING_OVERLAP");
        }
        foreach(string path in m.bindings.decor)
        {
            var t=stage.geometry.Find(path);if(!t)throw new Exception("ENVIRONMENT_DECOR_MISSING");
            foreach(var r in t.GetComponentsInChildren<Renderer>(true))
                if(r.bounds.min.y < .02f && r.bounds.max.y < .1f && r.bounds.Contains(Vector3.zero))throw new Exception("ENVIRONMENT_DECOR_HIDES_FLOOR: "+m.id+"/"+r.name);
        }
        bool floor=false;
        foreach(var r in renderers)
        {
            var b=r.bounds;
            if(b.size.magnitude>100 || b.min.y < -1)throw new Exception("ENVIRONMENT_SCALE_INVALID: "+r.name);
            if(b.max.y>=-.1f && b.max.y<=.08f && b.min.x<=-m.stage.clearRadius && b.max.x>=m.stage.clearRadius && b.min.z<=-m.stage.clearRadius && b.max.z>=m.stage.clearRadius)floor=true;
            float x=Mathf.Max(0,Mathf.Abs(b.center.x)-b.extents.x),z=Mathf.Max(0,Mathf.Abs(b.center.z)-b.extents.z);
            if(b.max.y>.12f && b.min.y<2.4f && x*x+z*z<m.stage.clearRadius*m.stage.clearRadius && m.source.kind!="builtin")throw new Exception("ENVIRONMENT_ACTOR_CLEARANCE: "+r.name);
        }
        if(!floor && m.source.kind!="builtin")throw new Exception("ENVIRONMENT_GROUND_MISSING");
    }
    public static void Thumbnails()
    {
        var director=UnityEngine.Object.FindFirstObjectByType<EnvironmentDirector>();if(!director)return;
        var camera=director.viewCamera;var position=camera.transform.position;var rotation=camera.transform.rotation;
        var fov=camera.fieldOfView;var aspect=camera.aspect;var previousTarget=camera.targetTexture;var previousActive=RenderTexture.active;
        var actors=UnityEngine.Object.FindFirstObjectByType<ViewerController>().characters;
        var actorVisibility=actors.Select(actor=>actor.gameObject.activeSelf).ToArray();
        var rt=new RenderTexture(480,320,24);rt.Create();
        try
        {
            foreach(var actor in actors)actor.gameObject.SetActive(false);
            camera.targetTexture=rt;camera.aspect=1.5f;camera.fieldOfView=38;
            // A level, centred architectural view keeps the finite rear scenery and
            // wall edges outside the frame while showing the real foreground depth.
            camera.transform.position=new Vector3(0,1.5f,4.2f);camera.transform.LookAt(new Vector3(0,1.5f,-2.8f));
            foreach(var stage in director.stages)
            {
                director.Bind(1.7f);director.Configure(new StudioSettings {room=stage.Manifest.id});RenderPipeline.SubmitRenderRequest(camera,new UniversalRenderPipeline.SingleCameraRequest {destination=rt});RenderTexture.active=rt;
                var image=new Texture2D(480,320,TextureFormat.RGB24,false);
                try
                {
                    image.ReadPixels(new Rect(0,0,480,320),0,0);image.Apply();
                    string name=stage.Manifest.display.thumbnail;string folder=Path.Combine(Root,"ios/CharacterHost/Resources/Assets.xcassets",name+".imageset");Directory.CreateDirectory(folder);
                    File.WriteAllBytes(Path.Combine(folder,name+".png"),image.EncodeToPNG());File.WriteAllText(Path.Combine(folder,"Contents.json"),"{\"images\":[{\"filename\":\""+name+".png\",\"idiom\":\"universal\"}],\"info\":{\"author\":\"xcode\",\"version\":1}}");
                }
                finally { UnityEngine.Object.DestroyImmediate(image); }
            }
        }
        finally
        {
            camera.targetTexture=previousTarget;RenderTexture.active=previousActive;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
            camera.transform.SetPositionAndRotation(position,rotation);camera.fieldOfView=fov;camera.aspect=aspect;
            for(int i=0;i<actors.Length;i++)actors[i].gameObject.SetActive(actorVisibility[i]);
            director.Bind(1.7f);director.Configure(new StudioSettings());
        }
    }
}
