#!/usr/bin/env python3
"""Generate a deterministic native Xcode project and workspace; no extra project tools.

The Unity project remains generated by Unity. Cross-project dependencies make Xcode
build UnityFramework before linking/embedding it in the native application.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import subprocess
from urllib.parse import urlsplit
import xml.sax.saxutils as xml
from generate_asset_credits import generate_asset_credits

ROOT = Path(__file__).resolve().parents[1]
test_tool_config=ROOT/'.local/character-ai-client/TestTools.json'
test_tools=os.environ.get('STARRY_TEST_TOOLS', '1' if test_tool_config.exists() and json.loads(test_tool_config.read_text()).get('enabled') else '0')=='1'
parser = argparse.ArgumentParser()
parser.add_argument('--platform', choices=['simulator', 'device'], default='simulator')
parser.add_argument('--distribution', action='store_true', help='Exclude developer UI and private AI inspection resources')
parser.add_argument('--native-ui-fixture', action='store_true', help='Isolated Debug simulator shell with a test-only bridge; no Unity or network configuration')
args = parser.parse_args()
if args.native_ui_fixture and (args.platform != 'simulator' or args.distribution):
    parser.error('Native UI fixtures are restricted to Debug simulator testing')
if args.distribution: test_tools=False
sdk = 'iphonesimulator' if args.platform == 'simulator' else 'iphoneos'
ios = ROOT / 'ios'
# Keep the physical-device workspace stable while simulator builds/tests run.
# Both projects stay beside CharacterHost/, preserving SRCROOT-relative paths.
project_name = 'CharacterHost-Simulator.xcodeproj' if args.platform == 'simulator' else 'CharacterHost.xcodeproj'
workspace_name = 'StarryNight-Simulator.xcworkspace' if args.platform == 'simulator' else 'StarryNight.xcworkspace'
if args.native_ui_fixture:
    project_name='CharacterHost-NativeUI.xcodeproj';workspace_name='StarryNight-NativeUI.xcworkspace'
export = ROOT / 'build' / f'unity-{args.platform}'
unity_path = export / 'Unity-iPhone.xcodeproj'
if not args.native_ui_fixture:
    if not unity_path.exists():
        raise SystemExit(f'Run Unity export first: {unity_path}')
    unity = json.loads(subprocess.check_output(['plutil','-convert','json','-o','-',str(unity_path/'project.pbxproj')]))
    utarget = next(k for k,v in unity['objects'].items() if v.get('isa') == 'PBXNativeTarget' and v.get('name') == 'UnityFramework')
    uproduct = unity['objects'][utarget]['productReference']
objects = {}

def uid(name): return hashlib.sha256(name.encode()).hexdigest()[:24].upper()
def obj(key, isa, **fields):
    value = uid(key); objects[value] = dict(isa=isa, **fields); return value
def buildfile(key, ref, **extra): return obj('build:'+key,'PBXBuildFile',fileRef=ref,**extra)
def configuration(key, settings):
    configs = [obj(f'{key}:{name}','XCBuildConfiguration',name=name,buildSettings=dict(settings,**(
        {'SWIFT_OPTIMIZATION_LEVEL':'-Onone','GCC_OPTIMIZATION_LEVEL':'0','DEBUG_INFORMATION_FORMAT':'dwarf','SWIFT_ACTIVE_COMPILATION_CONDITIONS':'$(inherited) DEBUG'+(' STARRY_TEST_TOOLS' if test_tools else '')} if name=='Debug' else
        {'SWIFT_OPTIMIZATION_LEVEL':'-O','GCC_OPTIMIZATION_LEVEL':'s','DEBUG_INFORMATION_FORMAT':'dwarf-with-dsym','SWIFT_ACTIVE_COMPILATION_CONDITIONS':'$(inherited)'+(' STARRY_TEST_TOOLS' if test_tools else '')}))) for name in ['Debug','Release']]
    if key in ('host','tests'):
        for config in configs: objects[config]['baseConfigurationReference'] = uid('base-config')
    return obj(key+':configs','XCConfigurationList',buildConfigurations=configs,defaultConfigurationIsVisible='0',defaultConfigurationName='Debug')

# Keep model authors, original licensing and separate upstream NOTICE files
# available offline in both About and each character's source-attribution page.
if not args.native_ui_fixture:generate_asset_credits(ROOT)
source_refs=[]; source_build=[]; resource_build=[]
active_music = {t['asset'] for c in json.loads((ios/'CharacterHost/Resources/CharacterCollections.json').read_text())['collections'] for t in c['music']}
for path in sorted((ios/'CharacterHost').rglob('*')):
    if any(p.suffix == '.xcassets' for p in path.parents): continue
    if path.suffix == '.xcassets':
        relative=str(path.relative_to(ios))
        ref=obj(relative,'PBXFileReference',lastKnownFileType='folder.assetcatalog',path=relative,sourceTree='<group>')
        source_refs.append(ref); resource_build.append(buildfile(relative,ref))
        continue
    if not path.is_file() or path.name == 'Info.plist': continue
    if args.native_ui_fixture and path.name == 'UnityRuntimeBridge.mm':continue
    if not test_tools and ('Developer' in path.parts or path.name == 'AIInspectionPanel.swift'): continue
    if path.name.startswith('Music_') and path.stem not in active_music: continue
    types={'.swift':'sourcecode.swift','.mm':'sourcecode.cpp.objcpp','.h':'sourcecode.c.h','.png':'image.png','.txt':'text','.json':'text.json','.wav':'audio.wav','.pcm':'file','.caf':'audio.caf','.storyboard':'file.storyboard','.xcstrings':'text.json.xcstrings'}
    if path.suffix not in types: continue
    relative=str(path.relative_to(ios))
    ref=obj(relative,'PBXFileReference',lastKnownFileType=types[path.suffix],path=relative,sourceTree='<group>')
    source_refs.append(ref)
    if path.suffix in ('.swift','.mm'): source_build.append(buildfile(relative,ref))
    elif path.suffix in ('.png','.txt','.json','.wav','.pcm', '.caf','.storyboard','.xcstrings'): resource_build.append(buildfile(relative,ref))
if args.native_ui_fixture:
    relative='../scripts/tests/NativeUIBridge.mm'
    ref=obj(relative,'PBXFileReference',lastKnownFileType='sourcecode.cpp.objcpp',path=relative,sourceTree='<group>')
    source_refs.append(ref);source_build.append(buildfile(relative,ref))

# Run the same pure Swift checks in the iOS runtime when local macOS executables
# cannot launch. The SceneDelegate entry is DEBUG + simulator + explicit flag only.
if args.platform == 'simulator':
    for test_name in ['MessageConversationFixture', 'AppLanguageFixture', 'ConversationContinuityFixture', 'CharacterOpeningChecks', 'VoiceAtmosphereFixture', 'ReplyFlowFixture', 'ConversationGestureFixture', 'ConversationPresentationFixture', 'ChatComposerInputTests', 'CloudSpeechPlaybackTests', 'CompanionExperienceTests', 'ConversationGreetingTests', 'ConversationExportTests', 'CharacterLibraryTests', 'AuthorSubscriptionTests', 'CacheStorageTests', 'CharacterViewPresetTests', 'MarketplaceCoreTests']:
        relative=f'../scripts/tests/{test_name}.swift'
        ref=obj(relative,'PBXFileReference',lastKnownFileType='sourcecode.swift',path=relative,sourceTree='<group>')
        source_refs.append(ref); source_build.append(buildfile(relative,ref))

# Restricted development gateway token only; the paid provider key is server-only.
if test_tools:
    rules=ROOT/'.local/character-ai-client/ClientAIRules.txt'
    rules.parent.mkdir(parents=True,exist_ok=True)
    names=('CompanionSession.swift','ConversationGreeting.swift','CloudSpeech.swift','SpeechClipCache.swift','CharacterAI.swift','ReplyReveal.swift','AIReplyContent.swift')
    rules.write_text('\n\n'.join('===== '+name+' =====\n'+(ios/'CharacterHost/Features/Companion'/name).read_text() for name in names))
    ref=obj('ai-test-rules','PBXFileReference',lastKnownFileType='text',path='../.local/character-ai-client/ClientAIRules.txt',sourceTree='<group>')
    source_refs.append(ref);resource_build.append(buildfile('ai-test-rules',ref))
# The platform endpoint is independently configurable; it contains no credentials.
platform_connection = ROOT/f'.local/platform-client/{args.platform}/PlatformConnection.json'
if not platform_connection.exists():
    platform_connection = ROOT/'.local/platform-client/PlatformConnection.json'
if not platform_connection.exists():
    platform_connection = ROOT/'config/PlatformConnection.json'
has_platform_connection = platform_connection.exists() and not args.native_ui_fixture
if has_platform_connection and args.platform == 'device':
    endpoint = json.loads(platform_connection.read_text()).get('baseURL', '')
    if urlsplit(endpoint).hostname in ('127.0.0.1', 'localhost'):
        has_platform_connection = False
if has_platform_connection:
    ref=obj('platform-connection','PBXFileReference',lastKnownFileType='text.json',path='../'+str(platform_connection.relative_to(ROOT)),sourceTree='<group>')
    source_refs.append(ref); resource_build.append(buildfile('platform-connection',ref))

# Production AI requests use the account session. Never ship the old shared
# worker token alongside a public HTTPS platform configuration.
uses_cloud_accounts = has_platform_connection and urlsplit(json.loads(platform_connection.read_text()).get('baseURL', '')).scheme == 'https'
connection = ROOT/'.local/character-ai-client/Connection.json'
if connection.exists() and not uses_cloud_accounts and not args.distribution and not args.native_ui_fixture:
    ref=obj('ai-connection','PBXFileReference',lastKnownFileType='text.json',path='../.local/character-ai-client/Connection.json',sourceTree='<group>')
    source_refs.append(ref); resource_build.append(buildfile('ai-connection',ref))

app=obj('app-product','PBXFileReference',explicitFileType='wrapper.application',path='CharacterHost.app',sourceTree='BUILT_PRODUCTS_DIR',includeInIndex='0')
if not args.native_ui_fixture:
    unity_ref=obj('unity-project','PBXFileReference',lastKnownFileType='wrapper.pb-project',path=f'../build/unity-{args.platform}/Unity-iPhone.xcodeproj',sourceTree='<group>')
    target_proxy=obj('unity-target-proxy','PBXContainerItemProxy',containerPortal=unity_ref,proxyType='1',remoteGlobalIDString=utarget,remoteInfo='UnityFramework')
    product_proxy=obj('unity-product-proxy','PBXContainerItemProxy',containerPortal=unity_ref,proxyType='2',remoteGlobalIDString=uproduct,remoteInfo='UnityFramework')
    framework=obj('unity-product','PBXReferenceProxy',fileType='wrapper.framework',path='UnityFramework.framework',remoteRef=product_proxy,sourceTree='BUILT_PRODUCTS_DIR')
    unity_products=obj('unity-products','PBXGroup',name='Products',children=[framework],sourceTree='<group>')
    dependency=obj('unity-dependency','PBXTargetDependency',name='UnityFramework',targetProxy=target_proxy)
products=obj('products','PBXGroup',name='Products',children=[app],sourceTree='<group>')
sources=obj('sources','PBXSourcesBuildPhase',buildActionMask='2147483647',files=source_build,runOnlyForDeploymentPostprocessing='0')
resources=obj('resources','PBXResourcesBuildPhase',buildActionMask='2147483647',files=resource_build,runOnlyForDeploymentPostprocessing='0')
frameworks=obj('frameworks','PBXFrameworksBuildPhase',buildActionMask='2147483647',files=[] if args.native_ui_fixture else [buildfile('link-unity',framework)],runOnlyForDeploymentPostprocessing='0')
embed=obj('embed','PBXCopyFilesBuildPhase',buildActionMask='2147483647',dstPath='',dstSubfolderSpec='10',name='Embed Frameworks',files=[] if args.native_ui_fixture else [buildfile('embed-unity',framework,settings={'ATTRIBUTES':['CodeSignOnCopy','RemoveHeadersOnCopy']})],runOnlyForDeploymentPostprocessing='0')
content_check=obj('check-content','PBXShellScriptBuildPhase',buildActionMask='2147483647',files=[],inputPaths=[],outputPaths=[],
    name='Check character content',runOnlyForDeploymentPostprocessing='0',shellPath='/bin/sh',alwaysOutOfDate='1',
    shellScript='set -e\nif [ "${ACTION:-}" = install ] && echo "${SWIFT_ACTIVE_COMPILATION_CONDITIONS:-}" | /usr/bin/grep -q STARRY_TEST_TOOLS; then\n  echo "error: Developer tools cannot be archived. Regenerate with scripts/generate_host.py --platform device --distribution."\n  exit 1\nfi\n'
        f'python3 "${{SRCROOT}}/../scripts/check_export_content.py" --platform {args.platform}\n'
        'python3 "${SRCROOT}/../scripts/check_character_openings.py"\n')
settings={'PRODUCT_NAME':'$(TARGET_NAME)','PRODUCT_BUNDLE_IDENTIFIER':'com.modelspace.viewer',
    'PRODUCT_BUNDLE_IDENTIFIER[sdk=iphoneos*]':'$(MODELSPACE_DEVICE_BUNDLE_IDENTIFIER)',
    'INFOPLIST_FILE':'../.local/native-ui-fixture/Info.plist' if args.native_ui_fixture else 'CharacterHost/Info.plist','SWIFT_VERSION':'6.0','SWIFT_OBJC_BRIDGING_HEADER':'CharacterHost/Bridge/CharacterHost-Bridging-Header.h',
    'IPHONEOS_DEPLOYMENT_TARGET':'17.0','TARGETED_DEVICE_FAMILY':'1,2','SDKROOT':sdk,
    # Each Unity export contains one Apple platform, even when both use arm64.
    # Offering both destinations lets the host build for Simulator while its
    # Unity dependency builds for Device, so their framework directories differ.
    'SUPPORTED_PLATFORMS':sdk,'CLANG_ENABLE_MODULES':'YES','CLANG_ENABLE_OBJC_ARC':'YES',
    'CLANG_CXX_LANGUAGE_STANDARD':'gnu++17','LD_RUNPATH_SEARCH_PATHS':['$(inherited)','@executable_path/Frameworks'],
    'FRAMEWORK_SEARCH_PATHS':['$(inherited)','$(BUILT_PRODUCTS_DIR)'],
    'OTHER_LDFLAGS':['$(inherited)','-lc++','-framework','CoreML','-framework','Accelerate'],
    'GCC_ENABLE_CPP_EXCEPTIONS':'YES',
    'CODE_SIGN_STYLE':'Automatic','CURRENT_PROJECT_VERSION':'119','MARKETING_VERSION':'0.89.0',
    'ENABLE_USER_SCRIPT_SANDBOXING':'NO','SUPPORTS_MACCATALYST':'NO','SWIFT_EMIT_LOC_STRINGS':'YES',
    'ARCHS':'arm64','ENABLE_DEBUG_DYLIB':'NO','ASSETCATALOG_COMPILER_APPICON_NAME':'AppIcon'}
if args.native_ui_fixture:
    settings['PRODUCT_BUNDLE_IDENTIFIER']='app.starrynight.native-ui-fixture'
    objects[content_check]['shellScript']='set -e\nif [ "${CONFIGURATION}" != Debug ] || [ "${ACTION:-}" = install ]; then echo "error: Native UI fixture is simulator-test-only"; exit 1; fi\n'
target=obj('host-target','PBXNativeTarget',name='CharacterHost',productName='CharacterHost',productType='com.apple.product-type.application',productReference=app,
    buildConfigurationList=configuration('host',settings),buildPhases=[content_check,sources,frameworks,resources,embed],buildRules=[],dependencies=[] if args.native_ui_fixture else [dependency])

# Native UI tests exercise the real installed app, including Unity's touch surface.
test_refs=[]; test_build=[]
for path in sorted(p for p in (ios/'CharacterHostUITests').iterdir() if p.suffix in ('.swift','.m')):
    relative=str(path.relative_to(ios))
    ref=obj(relative,'PBXFileReference',lastKnownFileType='sourcecode.c.objc' if path.suffix == '.m' else 'sourcecode.swift',path=relative,sourceTree='<group>')
    test_refs.append(ref); test_build.append(buildfile(relative,ref))
test_product=obj('test-product','PBXFileReference',explicitFileType='wrapper.cfbundle',path='CharacterHostUITests.xctest',sourceTree='BUILT_PRODUCTS_DIR')
test_sources=obj('test-sources','PBXSourcesBuildPhase',buildActionMask='2147483647',files=test_build,runOnlyForDeploymentPostprocessing='0')
test_frameworks=obj('test-frameworks','PBXFrameworksBuildPhase',buildActionMask='2147483647',files=[],runOnlyForDeploymentPostprocessing='0')
host_proxy=obj('host-proxy','PBXContainerItemProxy',containerPortal=uid('project'),proxyType='1',remoteGlobalIDString=target,remoteInfo='CharacterHost')
host_dependency=obj('host-dependency','PBXTargetDependency',target=target,targetProxy=host_proxy)
test_settings={'PRODUCT_NAME':'$(TARGET_NAME)','PRODUCT_BUNDLE_IDENTIFIER':'com.modelspace.viewer.uitests','GENERATE_INFOPLIST_FILE':'YES',
    'PRODUCT_BUNDLE_IDENTIFIER[sdk=iphoneos*]':'$(MODELSPACE_DEVICE_BUNDLE_IDENTIFIER).uitests',
    'SWIFT_VERSION':'6.0','IPHONEOS_DEPLOYMENT_TARGET':'17.0','TARGETED_DEVICE_FAMILY':'1,2','SDKROOT':sdk,
    'SUPPORTED_PLATFORMS':sdk,
    'SWIFT_OBJC_BRIDGING_HEADER':'CharacterHostUITests/InspectionEventSynthesis.h',
    'TEST_TARGET_NAME':'CharacterHost','CODE_SIGN_STYLE':'Automatic','CLANG_ENABLE_MODULES':'YES','ARCHS':'arm64'}
if args.native_ui_fixture:test_settings['PRODUCT_BUNDLE_IDENTIFIER']='app.starrynight.native-ui-fixture.uitests'
test_target=obj('test-target','PBXNativeTarget',name='CharacterHostUITests',productName='CharacterHostUITests',productType='com.apple.product-type.bundle.ui-testing',productReference=test_product,
    buildConfigurationList=configuration('tests',test_settings),buildPhases=[test_sources,test_frameworks],buildRules=[],dependencies=[host_dependency])
objects[products]['children'].append(test_product)
base_config=obj('base-config','PBXFileReference',lastKnownFileType='text.xcconfig',path='Config/Base.xcconfig',sourceTree='<group>')
main_group=obj('main-group','PBXGroup',children=source_refs+test_refs+[base_config]+([] if args.native_ui_fixture else [unity_ref])+[products],sourceTree='<group>')
project=obj('project','PBXProject',attributes={'BuildIndependentTargetsInParallel':'YES','LastUpgradeCheck':'2640','TargetAttributes':{target:{'CreatedOnToolsVersion':'26.4'},test_target:{'CreatedOnToolsVersion':'26.4','TestTargetID':target}}},
    buildConfigurationList=configuration('project',{'CLANG_ENABLE_MODULES':'YES','CLANG_ENABLE_OBJC_ARC':'YES'}),compatibilityVersion='Xcode 14.0',developmentRegion='zh-Hans',hasScannedForEncodings='0',knownRegions=['zh-Hans','zh-Hant','en','Base'],mainGroup=main_group,productRefGroup=products,projectDirPath='',projectRoot='',targets=[target,test_target],projectReferences=[] if args.native_ui_fixture else [{'ProductGroup':unity_products,'ProjectRef':unity_ref}])

def pbx(value):
    if isinstance(value,dict): return '{\n'+''.join(f'{json.dumps(str(k))} = {pbx(v)};\n' for k,v in value.items())+'}'
    if isinstance(value,list): return '('+','.join(pbx(v) for v in value)+')'
    return json.dumps(str(value),ensure_ascii=False)

project_dir=ios/project_name; project_dir.mkdir(parents=True,exist_ok=True)
(project_dir/'project.pbxproj').write_text('// !$*UTF8*$!\n'+pbx({'archiveVersion':'1','classes':{},'objectVersion':'56','objects':objects,'rootObject':project})+'\n')
workspace=ios/workspace_name; workspace.mkdir(exist_ok=True)
unity_workspace_ref='' if args.native_ui_fixture else f'<FileRef location="group:../build/unity-{args.platform}/Unity-iPhone.xcodeproj"/>'
(workspace/'contents.xcworkspacedata').write_text(f'<?xml version="1.0" encoding="UTF-8"?><Workspace version="1.0"><FileRef location="group:{project_name}"/>{unity_workspace_ref}</Workspace>\n')
def reference(identifier,name,product,container):
    return f'<BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="{identifier}" BuildableName="{product}" BlueprintName="{name}" ReferencedContainer="container:{container}"/>'
host_ref=reference(target,'CharacterHost','CharacterHost.app',project_name)
test_ref=reference(test_target,'CharacterHostUITests','CharacterHostUITests.xctest',project_name)
run_configuration = 'Release' if args.platform == 'device' else 'Debug'
scheme=f'''<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="2640" version="1.3">
 <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES"><BuildActionEntries>
  <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">{host_ref}</BuildActionEntry>
 </BuildActionEntries></BuildAction>
 <TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="NO" disablePerformanceAntipatternChecker="YES"><EnvironmentVariables><EnvironmentVariable key="STARRY_LIVE_AI_TESTS" value="{1 if os.environ.get('STARRY_LIVE_AI_TESTS') == '1' else 0}" isEnabled="YES"/></EnvironmentVariables><Testables><TestableReference skipped="NO">{test_ref}</TestableReference></Testables></TestAction>
 <LaunchAction buildConfiguration="{run_configuration}" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" allowLocationSimulation="YES" disablePerformanceAntipatternChecker="YES"><BuildableProductRunnable runnableDebuggingMode="0">{host_ref}</BuildableProductRunnable></LaunchAction>
 <ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES"><BuildableProductRunnable runnableDebuggingMode="0">{host_ref}</BuildableProductRunnable></ProfileAction>
 <AnalyzeAction buildConfiguration="Debug"/><ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
</Scheme>'''
schemes=workspace/'xcshareddata/xcschemes'; schemes.mkdir(parents=True,exist_ok=True)
(schemes/'CharacterHost.xcscheme').write_text(scheme)
info={'CFBundleDevelopmentRegion':'zh-Hans','CFBundleLocalizations':['zh-Hans','zh-Hant','en'],'CFBundleDisplayName':json.loads((ROOT/'assets/brand/brand.json').read_text())['displayName'],'CFBundleExecutable':'$(EXECUTABLE_NAME)',
    'CFBundleIdentifier':'$(PRODUCT_BUNDLE_IDENTIFIER)','CFBundleInfoDictionaryVersion':'6.0','CFBundleName':'$(PRODUCT_NAME)',
    'CFBundlePackageType':'APPL','CFBundleShortVersionString':'$(MARKETING_VERSION)','CFBundleVersion':'$(CURRENT_PROJECT_VERSION)',
    'NSMicrophoneUsageDescription':'将语音发送至星夜 AI 服务及阿里云百炼，实时转成可编辑文字。确认发送后才进入对话。',
    'NSMotionUsageDescription':'在对话中识别主动摇晃，让角色作出回应。运动数据仅在本机处理。',
    'NSLocalNetworkUsageDescription':'开发版连接同一网络中的星夜 AI 服务，完成真实对话和语音。',
    'NSAppTransportSecurity':{'NSAllowsLocalNetworking':True},
    'LSRequiresIPhoneOS':True,'UILaunchScreen':{'UIColorName':'LaunchNight'},'UIUserInterfaceStyle':'Dark',
    'UIApplicationSceneManifest':{'UIApplicationSupportsMultipleScenes':False,'UISceneConfigurations':{'UIWindowSceneSessionRoleApplication':[{'UISceneConfigurationName':'Model Space','UISceneDelegateClassName':'$(PRODUCT_MODULE_NAME).SceneDelegate'}]}},
    'UISupportedInterfaceOrientations':['UIInterfaceOrientationPortrait','UIInterfaceOrientationLandscapeLeft','UIInterfaceOrientationLandscapeRight'],
    'UISupportedInterfaceOrientations~ipad':['UIInterfaceOrientationPortrait','UIInterfaceOrientationPortraitUpsideDown','UIInterfaceOrientationLandscapeLeft','UIInterfaceOrientationLandscapeRight'],
    'CADisableMinimumFrameDurationOnPhone':True,'UIRequiresFullScreen':False}
info_path=ROOT/'.local/native-ui-fixture/Info.plist' if args.native_ui_fixture else ios/'CharacterHost/Info.plist'
info_path.parent.mkdir(parents=True,exist_ok=True)
info_path.write_bytes(plistlib.dumps(info,sort_keys=False))
print(f'Generated {workspace.relative_to(ROOT)} for {args.platform}; {len(source_build)} native sources.')
