#!/usr/bin/env python3
"""Generate a deterministic native Xcode project and workspace; no extra project tools.

The Unity project remains generated by Unity. Cross-project dependencies make Xcode
build UnityFramework before linking/embedding it in the native application.
"""
import argparse
import hashlib
import json
from pathlib import Path
import plistlib
import subprocess
import xml.sax.saxutils as xml

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--platform', choices=['simulator', 'device'], default='simulator')
args = parser.parse_args()
ios = ROOT / 'ios'
export = ROOT / 'build' / f'unity-{args.platform}'
unity_path = export / 'Unity-iPhone.xcodeproj'
if not unity_path.exists():
    raise SystemExit(f'Run Unity export first: {unity_path}')
unity = json.loads(subprocess.check_output(['plutil','-convert','json','-o','-',str(unity_path/'project.pbxproj')]))
utarget = next(k for k,v in unity['objects'].items() if v.get('isa') == 'PBXNativeTarget' and v.get('name') == 'UnityFramework')
uproduct = unity['objects'][utarget]['productReference']
objects = {}

def uid(name): return hashlib.sha256(name.encode()).hexdigest()[:24].upper()
def obj(key, isa, **fields):
    value = uid(key); objects[value] = dict(isa=isa, **fields); return value
def buildfile(key, ref, **extra): return obj('build:'+key,'PBXBuildFile',fileRef=ref,**extra)
def configuration(key, settings):
    configs = [obj(f'{key}:{name}','XCBuildConfiguration',name=name,buildSettings=dict(settings,**(
        {'SWIFT_OPTIMIZATION_LEVEL':'-Onone','GCC_OPTIMIZATION_LEVEL':'0','DEBUG_INFORMATION_FORMAT':'dwarf','SWIFT_ACTIVE_COMPILATION_CONDITIONS':'DEBUG'} if name=='Debug' else
        {'SWIFT_OPTIMIZATION_LEVEL':'-O','GCC_OPTIMIZATION_LEVEL':'s','DEBUG_INFORMATION_FORMAT':'dwarf-with-dsym'}))) for name in ['Debug','Release']]
    if key in ('host','tests'):
        for config in configs: objects[config]['baseConfigurationReference'] = uid('base-config')
    return obj(key+':configs','XCConfigurationList',buildConfigurations=configs,defaultConfigurationIsVisible='0',defaultConfigurationName='Debug')

source_refs=[]; source_build=[]; resource_build=[]
for path in sorted((ios/'CharacterHost').rglob('*')):
    if any(p.suffix == '.xcassets' for p in path.parents): continue
    if path.suffix == '.xcassets':
        relative=str(path.relative_to(ios))
        ref=obj(relative,'PBXFileReference',lastKnownFileType='folder.assetcatalog',path=relative,sourceTree='<group>')
        source_refs.append(ref); resource_build.append(buildfile(relative,ref))
        continue
    if not path.is_file() or path.name == 'Info.plist': continue
    types={'.swift':'sourcecode.swift','.mm':'sourcecode.cpp.objcpp','.h':'sourcecode.c.h','.png':'image.png','.txt':'text','.storyboard':'file.storyboard'}
    if path.suffix not in types: continue
    relative=str(path.relative_to(ios))
    ref=obj(relative,'PBXFileReference',lastKnownFileType=types[path.suffix],path=relative,sourceTree='<group>')
    source_refs.append(ref)
    if path.suffix in ('.swift','.mm'): source_build.append(buildfile(relative,ref))
    elif path.suffix in ('.png','.txt','.storyboard'): resource_build.append(buildfile(relative,ref))

app=obj('app-product','PBXFileReference',explicitFileType='wrapper.application',path='CharacterHost.app',sourceTree='BUILT_PRODUCTS_DIR',includeInIndex='0')
unity_ref=obj('unity-project','PBXFileReference',lastKnownFileType='wrapper.pb-project',path=f'../build/unity-{args.platform}/Unity-iPhone.xcodeproj',sourceTree='<group>')
target_proxy=obj('unity-target-proxy','PBXContainerItemProxy',containerPortal=unity_ref,proxyType='1',remoteGlobalIDString=utarget,remoteInfo='UnityFramework')
product_proxy=obj('unity-product-proxy','PBXContainerItemProxy',containerPortal=unity_ref,proxyType='2',remoteGlobalIDString=uproduct,remoteInfo='UnityFramework')
framework=obj('unity-product','PBXReferenceProxy',fileType='wrapper.framework',path='UnityFramework.framework',remoteRef=product_proxy,sourceTree='BUILT_PRODUCTS_DIR')
unity_products=obj('unity-products','PBXGroup',name='Products',children=[framework],sourceTree='<group>')
dependency=obj('unity-dependency','PBXTargetDependency',name='UnityFramework',targetProxy=target_proxy)
products=obj('products','PBXGroup',name='Products',children=[app],sourceTree='<group>')
sources=obj('sources','PBXSourcesBuildPhase',buildActionMask='2147483647',files=source_build,runOnlyForDeploymentPostprocessing='0')
resources=obj('resources','PBXResourcesBuildPhase',buildActionMask='2147483647',files=resource_build,runOnlyForDeploymentPostprocessing='0')
frameworks=obj('frameworks','PBXFrameworksBuildPhase',buildActionMask='2147483647',files=[buildfile('link-unity',framework)],runOnlyForDeploymentPostprocessing='0')
embed=obj('embed','PBXCopyFilesBuildPhase',buildActionMask='2147483647',dstPath='',dstSubfolderSpec='10',name='Embed Frameworks',files=[buildfile('embed-unity',framework,settings={'ATTRIBUTES':['CodeSignOnCopy','RemoveHeadersOnCopy']})],runOnlyForDeploymentPostprocessing='0')
settings={'PRODUCT_NAME':'$(TARGET_NAME)','PRODUCT_BUNDLE_IDENTIFIER':'com.modelspace.viewer',
    'PRODUCT_BUNDLE_IDENTIFIER[sdk=iphoneos*]':'$(MODELSPACE_DEVICE_BUNDLE_IDENTIFIER)',
    'INFOPLIST_FILE':'CharacterHost/Info.plist','SWIFT_VERSION':'6.0','SWIFT_OBJC_BRIDGING_HEADER':'CharacterHost/Bridge/CharacterHost-Bridging-Header.h',
    'IPHONEOS_DEPLOYMENT_TARGET':'17.0','TARGETED_DEVICE_FAMILY':'1,2','SDKROOT':'iphoneos',
    'SUPPORTED_PLATFORMS':'iphoneos iphonesimulator','CLANG_ENABLE_MODULES':'YES','CLANG_ENABLE_OBJC_ARC':'YES',
    'CLANG_CXX_LANGUAGE_STANDARD':'gnu++17','LD_RUNPATH_SEARCH_PATHS':['$(inherited)','@executable_path/Frameworks'],
    'FRAMEWORK_SEARCH_PATHS':['$(inherited)','$(BUILT_PRODUCTS_DIR)'],
    'CODE_SIGN_STYLE':'Automatic','CURRENT_PROJECT_VERSION':'1','MARKETING_VERSION':'1.0',
    'ENABLE_USER_SCRIPT_SANDBOXING':'NO','SUPPORTS_MACCATALYST':'NO','SWIFT_EMIT_LOC_STRINGS':'YES',
    'ARCHS':'arm64','ENABLE_DEBUG_DYLIB':'NO','ASSETCATALOG_COMPILER_APPICON_NAME':'AppIcon'}
target=obj('host-target','PBXNativeTarget',name='CharacterHost',productName='CharacterHost',productType='com.apple.product-type.application',productReference=app,
    buildConfigurationList=configuration('host',settings),buildPhases=[sources,frameworks,resources,embed],buildRules=[],dependencies=[dependency])

# Native UI tests exercise the real installed app, including Unity's touch surface.
test_refs=[]; test_build=[]
for path in sorted((ios/'CharacterHostUITests').glob('*.swift')):
    relative=str(path.relative_to(ios))
    ref=obj(relative,'PBXFileReference',lastKnownFileType='sourcecode.swift',path=relative,sourceTree='<group>')
    test_refs.append(ref); test_build.append(buildfile(relative,ref))
test_product=obj('test-product','PBXFileReference',explicitFileType='wrapper.cfbundle',path='CharacterHostUITests.xctest',sourceTree='BUILT_PRODUCTS_DIR')
test_sources=obj('test-sources','PBXSourcesBuildPhase',buildActionMask='2147483647',files=test_build,runOnlyForDeploymentPostprocessing='0')
test_frameworks=obj('test-frameworks','PBXFrameworksBuildPhase',buildActionMask='2147483647',files=[],runOnlyForDeploymentPostprocessing='0')
host_proxy=obj('host-proxy','PBXContainerItemProxy',containerPortal=uid('project'),proxyType='1',remoteGlobalIDString=target,remoteInfo='CharacterHost')
host_dependency=obj('host-dependency','PBXTargetDependency',target=target,targetProxy=host_proxy)
test_settings={'PRODUCT_NAME':'$(TARGET_NAME)','PRODUCT_BUNDLE_IDENTIFIER':'com.modelspace.viewer.uitests','GENERATE_INFOPLIST_FILE':'YES',
    'PRODUCT_BUNDLE_IDENTIFIER[sdk=iphoneos*]':'$(MODELSPACE_DEVICE_BUNDLE_IDENTIFIER).uitests',
    'SWIFT_VERSION':'6.0','IPHONEOS_DEPLOYMENT_TARGET':'17.0','TARGETED_DEVICE_FAMILY':'1,2','SDKROOT':'iphoneos',
    'TEST_TARGET_NAME':'CharacterHost','CODE_SIGN_STYLE':'Automatic','CLANG_ENABLE_MODULES':'YES','ARCHS':'arm64'}
test_target=obj('test-target','PBXNativeTarget',name='CharacterHostUITests',productName='CharacterHostUITests',productType='com.apple.product-type.bundle.ui-testing',productReference=test_product,
    buildConfigurationList=configuration('tests',test_settings),buildPhases=[test_sources,test_frameworks],buildRules=[],dependencies=[host_dependency])
objects[products]['children'].append(test_product)
base_config=obj('base-config','PBXFileReference',lastKnownFileType='text.xcconfig',path='Config/Base.xcconfig',sourceTree='<group>')
main_group=obj('main-group','PBXGroup',children=source_refs+test_refs+[base_config,unity_ref,products],sourceTree='<group>')
project=obj('project','PBXProject',attributes={'BuildIndependentTargetsInParallel':'YES','LastUpgradeCheck':'2640','TargetAttributes':{target:{'CreatedOnToolsVersion':'26.4'},test_target:{'CreatedOnToolsVersion':'26.4','TestTargetID':target}}},
    buildConfigurationList=configuration('project',{'CLANG_ENABLE_MODULES':'YES','CLANG_ENABLE_OBJC_ARC':'YES'}),compatibilityVersion='Xcode 14.0',developmentRegion='zh-Hans',hasScannedForEncodings='0',knownRegions=['zh-Hans','en','Base'],mainGroup=main_group,productRefGroup=products,projectDirPath='',projectRoot='',targets=[target,test_target],projectReferences=[{'ProductGroup':unity_products,'ProjectRef':unity_ref}])

def pbx(value):
    if isinstance(value,dict): return '{\n'+''.join(f'{json.dumps(str(k))} = {pbx(v)};\n' for k,v in value.items())+'}'
    if isinstance(value,list): return '('+','.join(pbx(v) for v in value)+')'
    return json.dumps(str(value),ensure_ascii=False)

project_dir=ios/'CharacterHost.xcodeproj'; project_dir.mkdir(parents=True,exist_ok=True)
(project_dir/'project.pbxproj').write_text('// !$*UTF8*$!\n'+pbx({'archiveVersion':'1','classes':{},'objectVersion':'56','objects':objects,'rootObject':project})+'\n')
workspace=ios/'CharacterPrototype.xcworkspace'; workspace.mkdir(exist_ok=True)
(workspace/'contents.xcworkspacedata').write_text(f'<?xml version="1.0" encoding="UTF-8"?><Workspace version="1.0"><FileRef location="group:CharacterHost.xcodeproj"/><FileRef location="group:../build/unity-{args.platform}/Unity-iPhone.xcodeproj"/></Workspace>\n')
def reference(identifier,name,product,container):
    return f'<BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="{identifier}" BuildableName="{product}" BlueprintName="{name}" ReferencedContainer="container:{container}"/>'
host_ref=reference(target,'CharacterHost','CharacterHost.app','CharacterHost.xcodeproj')
test_ref=reference(test_target,'CharacterHostUITests','CharacterHostUITests.xctest','CharacterHost.xcodeproj')
run_configuration = 'Release' if args.platform == 'device' else 'Debug'
scheme=f'''<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="2640" version="1.3">
 <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES"><BuildActionEntries>
  <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">{host_ref}</BuildActionEntry>
 </BuildActionEntries></BuildAction>
 <TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES" disablePerformanceAntipatternChecker="YES"><Testables><TestableReference skipped="NO">{test_ref}</TestableReference></Testables></TestAction>
 <LaunchAction buildConfiguration="{run_configuration}" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" allowLocationSimulation="YES" disablePerformanceAntipatternChecker="YES"><BuildableProductRunnable runnableDebuggingMode="0">{host_ref}</BuildableProductRunnable></LaunchAction>
 <ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES"><BuildableProductRunnable runnableDebuggingMode="0">{host_ref}</BuildableProductRunnable></ProfileAction>
 <AnalyzeAction buildConfiguration="Debug"/><ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
</Scheme>'''
schemes=workspace/'xcshareddata/xcschemes'; schemes.mkdir(parents=True,exist_ok=True)
(schemes/'CharacterHost.xcscheme').write_text(scheme)
info={'CFBundleDevelopmentRegion':'zh_CN','CFBundleDisplayName':'模型空间','CFBundleExecutable':'$(EXECUTABLE_NAME)',
    'CFBundleIdentifier':'$(PRODUCT_BUNDLE_IDENTIFIER)','CFBundleInfoDictionaryVersion':'6.0','CFBundleName':'$(PRODUCT_NAME)',
    'CFBundlePackageType':'APPL','CFBundleShortVersionString':'$(MARKETING_VERSION)','CFBundleVersion':'$(CURRENT_PROJECT_VERSION)',
    'LSRequiresIPhoneOS':True,'UILaunchScreen':{},'UIUserInterfaceStyle':'Light',
    'UIApplicationSceneManifest':{'UIApplicationSupportsMultipleScenes':False,'UISceneConfigurations':{'UIWindowSceneSessionRoleApplication':[{'UISceneConfigurationName':'Model Space','UISceneDelegateClassName':'$(PRODUCT_MODULE_NAME).SceneDelegate'}]}},
    'UISupportedInterfaceOrientations':['UIInterfaceOrientationPortrait'],
    'UISupportedInterfaceOrientations~ipad':['UIInterfaceOrientationPortrait','UIInterfaceOrientationPortraitUpsideDown','UIInterfaceOrientationLandscapeLeft','UIInterfaceOrientationLandscapeRight'],
    'CADisableMinimumFrameDurationOnPhone':True,'UIRequiresFullScreen':False}
(ios/'CharacterHost/Info.plist').write_bytes(plistlib.dumps(info,sort_keys=False))
print(f'Generated CharacterHost workspace for {args.platform}; {len(source_build)} native sources.')
